apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment-green
  labels:
    type: backend-app
    deployment: green
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend-app
      deployment: green
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend-app
        deployment: green
    spec:
      containers:
        - name: app-api-green
          image: gyuho0897/matfia-app-api:1.1
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: app-api-config
